"""Data models for the research assistant."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional


@dataclass
class SearchResult:
    """Result from a web search."""
    url: str
    title: str
    snippet: str


@dataclass
class Source:
    """Web source with fetched content."""
    url: str
    title: str
    content: str
    fetch_time: datetime = field(default_factory=datetime.now)


@dataclass
class Fact:
    """Extracted fact from a source."""
    claim: str
    caveat: Optional[str]
    confidence: str  # "high", "medium", or "low"
    source_url: str


@dataclass
class Contradiction:
    """Contradiction found between sources."""
    issue: str
    sources: List[str]
    explanation: str


@dataclass
class Synthesis:
    """Synthesized findings from multiple sources."""
    agreements: List[str]
    contradictions: List[Contradiction]
    gaps: List[str]
    answer: str


@dataclass
class ResearchReport:
    """Complete research report."""
    question: str
    sub_queries: List[str]
    sources: List[Source]
    facts: List[Fact]
    synthesis: Synthesis
    timestamp: datetime = field(default_factory=datetime.now)

    def to_markdown(self) -> str:
        """
        Generate markdown formatted report.

        Returns:
            Markdown string
        """
        md = []

        # Header
        md.append(f"# Research Report: {self.question}")
        md.append(f"\n*Generated on {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}*\n")

        # Summary section
        md.append("## Summary\n")
        md.append(self.synthesis.answer)
        md.append("\n")

        # Key Findings section
        md.append("## Key Findings\n")
        for fact in self.facts:
            confidence_emoji = {
                'high': '✓',
                'medium': '○',
                'low': '?'
            }.get(fact.confidence.lower(), '○')

            md.append(f"- {confidence_emoji} **{fact.claim}**")
            if fact.caveat:
                md.append(f"  - *Caveat: {fact.caveat}*")
            md.append(f"  - Source: [{fact.source_url}]({fact.source_url})")
            md.append("")

        # Source Comparison section
        md.append("## Source Comparison\n")

        # Agreements
        if self.synthesis.agreements:
            md.append("### Areas of Agreement\n")
            for agreement in self.synthesis.agreements:
                md.append(f"- {agreement}")
            md.append("")

        # Contradictions
        if self.synthesis.contradictions:
            md.append("### Contradictions and Discrepancies\n")
            for contradiction in self.synthesis.contradictions:
                md.append(f"- **{contradiction.issue}**")
                md.append(f"  - Sources: {', '.join(contradiction.sources)}")
                md.append(f"  - Explanation: {contradiction.explanation}")
                md.append("")

        # Knowledge gaps
        if self.synthesis.gaps:
            md.append("### Knowledge Gaps\n")
            for gap in self.synthesis.gaps:
                md.append(f"- {gap}")
            md.append("")

        # References section
        md.append("## References\n")
        for idx, source in enumerate(self.sources, 1):
            md.append(f"{idx}. [{source.title}]({source.url})")
            md.append(f"   - Accessed: {source.fetch_time.strftime('%Y-%m-%d %H:%M:%S')}")
            md.append("")

        # Research methodology
        md.append("## Research Methodology\n")
        md.append(f"This report was generated by breaking down the question into {len(self.sub_queries)} sub-queries:")
        md.append("")
        for idx, query in enumerate(self.sub_queries, 1):
            md.append(f"{idx}. {query}")
        md.append(f"\nA total of {len(self.sources)} sources were consulted, ")
        md.append(f"from which {len(self.facts)} key facts were extracted and synthesized.\n")

        return "\n".join(md)
